# -*- coding: utf-8 -*-
"""HW2_Juan Velasquez_BAN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KrMbveUMO8M8WvQLoDnbPQ-e292wPzpq

HW 2 recording BAN_Juan Velasquez

1) Gaussian Random Number: Gaussian random numbers. One way to generate a random number taken from the
Gaussian distribution is to use the Box-Muller formula:
𝑍 = 𝑠𝑖𝑛(2 𝜋 𝑣)(−2 𝑙𝑛 𝑢)
1
2
where u and v are real numbers between 0 and 1 generated by the random.random() function.
Compose a program that writes a standard Gaussian random variable. And calculate 𝑍 value.
"""

import math as m, random as r

u, v = r.random(), r.random()
z = m.sin(2 * m.pi * v) * m.sqrt(-2 * m.log(u))

print(f"Z value: {z}")

import math
import random

# generate two uniform random #s between 0 & 1
U=random.random()
V=random.random()

#apply the box-muller formula
z=math.sin(2*math.pi*V)*math.sqrt(-2*math.log(U))

print(f"The calculated Z value is: {z}")

"""2) Write a program that takes two integer values a and b from the command line and prints
them in ascending order, separated by a space.
"""

import sys

# Define numbers directly for notebook execution
# For command-line execution, you would pass these as arguments:
# For example: !python your_script.py 5 2
num1 = 5
num2 = 2

# Convert arguments to integers and sort them
nums = sorted([num1, num2])
print(*nums) # The * unpacks the list to print with a space

import sys

# Gets args, converts to int, and sorts them
nums = sorted([int(sys.argv[1]), int(sys.argv[2])])
print(*nums)

# This avoids sys.argv entirely to prevent notebook errors
try:
    val_a = int(input("Enter first integer (a): "))
    val_b = int(input("Enter second integer (b): "))

    print(*sorted([val_a, val_b]))
except ValueError:
    print("Please ensure you enter whole numbers only.")

"""3)Write a program that takes three double values x, y, and z as command-line arguments
and prints True if the values are strictly ascending or descending (i.e., x < y < z or x > y > z), and
False otherwise.

"""

import sys

# For notebook execution, define values directly or use input()
x = 1.0  # Example value
y = 2.0  # Example value
z = 3.0  # Example value

# If running as a script from the command line, uncomment these lines:
# x = float(sys.argv[1])
# y = float(sys.argv[2])
# z = float(sys.argv[3])

# Check for x < y < z or x > y > z
is_ordered = (x < y < z) or (x > y > z)

print(is_ordered)

# Use these variables to test different scenarios in your notebook
x, y, z = 10.5, 20.0, 35.2

# A single line to check both strictly ascending and descending orders
is_ordered = (x < y < z) or (x > y > z)

print(is_ordered)

"""4) The following table contains earthquake magnitude ranges on the Richter scale and
their descriptors:
Magnitude
"""

magnitude = float(input("Enter the earthquake magnitude: "))

if magnitude < 2.0:
    descriptor = "Micro"
elif magnitude < 3.0:
    descriptor = "Very minor"
elif magnitude < 4.0:
    descriptor = "Minor"
elif magnitude < 5.0:
    descriptor = "Light"
elif magnitude < 6.0:
    descriptor = "Moderate"
elif magnitude < 7.0:
    descriptor = "Strong"
elif magnitude < 8.0:
    descriptor = "Major"
elif magnitude < 10.0:
    descriptor = "Great"
else:
    descriptor = "Meteoric"

print(f"A magnitude {magnitude} earthquake is considered to be a {descriptor} earthquake.")

"""5) What is printed by the Python code?"""

print(range(1,22,3))

"""6) What is printed by the Python code?"""

s = 'I ate it.'
print(s.upper())
print( s.count('t'))
w = s.split()
print(w)